In [1]:
# from: https://www.youtube.com/watch?v=BzcBsTou0C0

import torch
x = torch.Tensor([5, 3])
y = torch.Tensor([2, 1])

print(x * y)


tensor([10.,  3.])


In [3]:
x = torch.zeros(2, 5)

print(x)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


In [4]:
x.shape

torch.Size([2, 5])

In [7]:
y = torch.rand([2 , 5])
print(y)

tensor([[0.5778, 0.2164, 0.1117, 0.7001, 0.6338],
        [0.0633, 0.3362, 0.8906, 0.2728, 0.2317]])


In [8]:
y = y.view([1, 10])


In [9]:
y

tensor([[0.5778, 0.2164, 0.1117, 0.7001, 0.6338, 0.0633, 0.3362, 0.8906, 0.2728,
         0.2317]])